server:
 servlet:
    context-path: /farmacia-pedido/api

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://joao:lucas@cluster0.ck9mmqn.mongodb.net/cluster0?retryWrites=true&w=majority}
      auto-index-creation: true 

springdoc:
  swagger-ui:
    path: /public/swagger
 
  