server:
 servlet:
    context-path: /farmacia-pedido/api

spring:
  datasource:
    url: jdbc:h2:mem:demodb
    username: sa
    password: 
    driverClassName: 
    
  h2:
    console:
      enabled: true
      path: /h2-console
  